version: '3.4'

services:
    php:
        build:
            context: ./
            dockerfile: ./.docker/app/Dockerfile
        container_name: app
        ports:
            - '8000:8000'
        tty: true
        volumes:
            - ./app:/var/www/html
            - ./.docker/app/ini/:/usr/local/etc/php/conf.d
